python_data_analytics/07_Desenvolvimento Web/Django/mysite/mysite/urls.py
# from django.contrib import admin
from django.urls import include, path

# from polls.views import index as index
from .admin import admin_site

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', admin_site.urls),  # Alterando página admin
    # Rotas intrínsecas, modularize o código adicionado um urls.py em polls
    # path('polls/', index),
    # Recupera as rotas em polls
    path('polls/', include('polls.urls')),
    path('contacts/', include('contacts.urls')),
    path('accounts/', include('accounts.urls')),
]

# Criando superusuário para rota admin/
# ./manage.py createsuperuser

python_data_analytics/07_Desenvolvimento Web/Django/mysite/polls/urls.py
from django.urls import path

from . import views

# Nome da aplicação, impede ambiguidade ao referenciar métodos
app_name = 'polls'
# Rotas de polls, prefixo - método - identificador. Devem ser incluídos na configuração principal
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='result'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]
# Execute com ./manage.py runserver

python_data_analytics/07_Desenvolvimento Web/Django/mysite/polls/models.py
from datetime import timedelta

from django.db import models
from django.utils import timezone

# Create your models here.


# Criando os modelos do ORM
# ./manage.py makemigrations para criar migration e ./manage.py migrate para realizar upgrade
# ./manage.py migrate polls para especificar app
class Question(models.Model):
    question_text = models.CharField('Texto da questão', max_length=200)
    pub_date = models.DateTimeField('Data publicado')
    active = models.BooleanField('Ativo', default=True)
    # Campo que não aceita nulos por padrão é necessário default, Django propõe soluções automáticas para o erro quando executado.
    x = models.TextField(default='')
    # Rollback: ./manage.py migrate polls 0002

    class Meta:
        # Alterando metadados, verbose_name para nome usado na template
        # Traduzindo templates
        verbose_name = 'Questão'
        verbose_name_plural = 'Questões'

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - timedelta(days=1)

    def __str__(self):
        # Usado para representar os objetos, caso contrário é retornado <Question: Question object (n)>
        return f'{self.id}: {self.question_text}'


class Choice(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, verbose_name='Questão'
    )
    choice_text = models.CharField('Texto da escolha', max_length=200)
    votes = models.IntegerField('Votos', default=0)

    class Meta:
        verbose_name = 'Escolha'
        verbose_name_plural = 'Escolhas'

    def __str__(self):
        return f'{self.id}: {self.choice_text}'


# Usando o shell para manipular os modelos: ./manage.py shell. Use o módulo ipython para melhor interface

# from polls.models import Question, Choice
# from django.utils import timezone

# q = Question(question_text='Pergunta', pub_date=timezone.now())
# q.save()
# q.id, q.question_text

# q = Question.objects.all()
# Question.objects.filter(active=True)

# q[0].question_text = 'O que é Django?'
# q.save()

# Questions.objects.get(id=1)
# Questions.objects.first()
# c = Choice(question=Question.objects.get(id=1), choice_text='Django é um framework de desenvolvimento web...')
# c.save()

# Question.objects.get(question_text__icontains='Django')
# Question.objects.update(), .delete(), ...

python_data_analytics/07_Desenvolvimento Web/Django/mysite/polls/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse

from .models import Choice, Question

# Create your views here.


# Views do MTV ou Controladores do MVC
# Orquestram as requisições da aplicação
# def index(request):
#     # Prática não recomendada, ineficiente e insegura
#     html = """\
#     <h1>Index</h1>
#     <p>You're at the index page of polls.</p>
# """
#     return HttpResponse(html)


# def index(request):
#     latest_question_list = Question.objects.order_by('pub_date')[:5]
#     response = '<br>'.join([q.question_text for q in latest_question_list])
#     return HttpResponse(response)


# Recuperando template para index
def index(request):
    latest_question_list = Question.objects.order_by('pub_date')[:5]
    # Procura por um diretório de templates na pasta da aplicação polls
    template = loader.get_template('polls/index.html')
    # Mapeia os valores de variáveis descritas no template
    context = {'latest_question_list': latest_question_list}
    # Monta o arquivo HTML corretamente, substituindo variáveis por valores válidos
    return HttpResponse(template.render(context, request))


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404('Question does not exists')

    # render é uma shorthand para o processo de carregar templates acima
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    # Shortcut para o tratamento de erro acima
    question = get_object_or_404(Question, pk=question_id)

    return render(request, 'polls/result.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            'polls/detail.html',
            {'question': question, 'error_message': "You didn't select a choice."},
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:result', args=(question.id,)))

python_data_analytics/07_Desenvolvimento Web/Django/mysite/polls/templates/polls/detail.html
<!--Formulário que envia os resultados para o endpoint vote, com método POST-->
<form action="{% url 'polls:vote' question.id %}" method="post">
  <!--Previne ataques CSRF-->
  {% csrf_token %}
  <fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>

    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %} {% for choice in question.choice_set.all %}

    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    <br />

    {% endfor %}
  </fieldset>
  <input type="submit" value="vote" />
</form>

python_data_analytics/07_Desenvolvimento Web/Django/mysite/polls/templates/polls/index.html
<!--Criando uma template com Django Template Engine-->
{% if latest_question_list %}
<!--Se a variável tiver conteúdo, retorne este elemento HTML-->
<ul>
  {% for question in latest_question_list %}
  <!--Para cada questão dentro da lista, faça isso-->
  <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
  <!--Retorne uma lista com um link em /polls/question.id e o texto de question-->
  <!--\{{ }\} indica um data binding ou acesso a uma variável-->

  <!--Também pode ser feito com a tag especial do Django-->
  <!--<a href={\% url 'polls:detail' question.id %\}>{\{ question.question_text \}}</a>-->
  <!--Usa o atributo name dos métodos para construir a url-->
  {% endfor %}
  <!--Fim do loop-->
</ul>
{% else %}
<p>polls are not available</p>
{% endif %}
<!--Fim do if-->

python_data_analytics/07_Desenvolvimento Web/Django/mysite/polls/templates/polls/result.html
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
  <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
  {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Votar Novamente?</a>